FROM golang:1.22-alpine AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /router ./cmd/router

FROM alpine:3.19
RUN apk --no-cache add ca-certificates wget
COPY --from=builder /router /router
COPY config.yaml /config.yaml
EXPOSE 80 9091
ENTRYPOINT ["/router"]