FROM golang:1.22-alpine AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /origin ./cmd/origin

FROM alpine:3.24
RUN apk --no-cache add ca-certificates wget
COPY --from=builder /origin /origin
COPY config.yaml /config.yaml
EXPOSE 9090
ENTRYPOINT ["/origin"]